title: <b>The Security Operations Library/b>
description: A collection of quick reference materials and guides for security operators
theme: just-the-docs
color_scheme: dark

url: https://just-the-docs.github.io

aux_links:
  Questions? Contact: https://chatala1.github.io/chatala1
